CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    registration TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    INDEX (username)
);